### ISSUE TITLE
impound Paleto

### ISSUE THREAD

**Issue by Andyauk** [JonasDev99/qb-garages#1]
I was driving to Paleto Bay, and server restarted. when I got back in. it said my car was back at pillbox. but it was in impound. like it should. but the phone said other. not sure if its any help to you.

**Comment by JonasDev99** [comment]
Thanks, I will look into it!

**Comment by Andyauk** [comment]
> Thanks, I will look into it!

thank you. keep up the great work.

**Comment by JonasDev99** [comment]
Think it should say Status: Out, but garage should still say the last garage the car was in

**Comment by JonasDev99** [comment]
Please check if its fixed in the latest update
