### ISSUE TITLE
AutoRespawn and depot bug

### ISSUE THREAD

**Issue by Baelroak** [JonasDev99/qb-garages#11]
If your vehicle is in a depot and the city restarts causing the AutoRespawn funtion to trigger, it will set the state of the vehicle to 1 for stored in garage but doesn't change stored location, depot only detects vehicles in it if they are in state 0 or 2 according to line 47 in server\main.lua

`MySQL.Async.fetchAll('SELECT * FROM player_vehicles WHERE citizenid = ? AND (state = ? OR state = ?)', {pData.PlayerData.citizenid, 0, 2}, function(result)`

replace with 

`MySQL.Async.fetchAll('SELECT * FROM player_vehicles WHERE citizenid = ? AND (state = ? OR state = ? or garage = ?)', {pData.PlayerData.citizenid, 0, 2, "impoundlot"}, function(result)`

all it does is add an extra check for what garage its stored in, if its the impound it will return a result the same as if it was in state 0, 2

"impoundlot" is the name of the depot, if you have multiple depots you can just gopy and paste `or garage = ?` after the first one and put a comma after your first depots name and then write your second depots name like this` , 0, 2, "depot1", "depot2"}, function(result)`

**Comment by JonasDev99** [comment]
Thanks, I will look into this 👍
