### ISSUE TITLE
SharedGarages not working

### ISSUE THREAD

**Issue by Peple77** [JonasDev99/qb-garages#15]
I set SharedGarages to true in the config but whenever I open the police garage it only has my vehicles in it, there is other vehicles in that garage that aren't owned by me but I can't see them on the list.
![image](https://user-images.githubusercontent.com/98569110/165779789-2538db37-2a2e-439a-8488-116864b7d95c.png)
![image](https://user-images.githubusercontent.com/98569110/165779886-6e0f7218-cddc-4dd9-bfca-4ea181d2537f.png)

**Comment by JonasDev99** [comment]
I gotta look into that option but there is specifically a SharedJobGarages option where you can add the garage police.

**Comment by NiZiBiiT** [comment]
I am having the same issue. Set the shared garage to true but nothing is being shared within job garages

**Comment by JonasDev99** [comment]
> I am having the same issue. Set the shared garage to true but nothing is being shared within job garages

Add your garage to the SharedJobGarages list

**Comment by NiZiBiiT** [comment]
> > I am having the same issue. Set the shared garage to true but nothing is being shared within job garages
> 
> Add your garage to the SharedJobGarages list

Where do I find this please?

**Comment by JonasDev99** [comment]
![image](https://user-images.githubusercontent.com/25738474/168280793-89d34730-c327-44f3-aa49-37e5810354c1.png)
