### ISSUE TITLE
Does not work on most recent qb-core.

### ISSUE THREAD

**Issue by GetBackJames** [JonasDev99/qb-garages#24]
Throwing the same field errors listed below and broke are fueling system.

**Comment by JonasDev99** [comment]
Listed below? Also make sure you set the fueling system in the config to the one you use

**Comment by GetBackJames** [comment]
Ok I got the fuel sorted I believe but do you have a vehicle shop you recommend because it throws the field errors listed in the error below.

**Comment by JonasDev99** [comment]
Can you show me what line it is? I just updated the script so the lines don't match anymore.

**Comment by GetBackJames** [comment]
I would if I could I just updated my oxmysql and now I get this error. Im getting this for multiple script and I gotta figure out a fix.

![image](https://user-images.githubusercontent.com/101968218/169769288-6972f0dd-efd7-4556-a2d9-957fa6bc4450.png)

**Comment by JonasDev99** [comment]
Ok, looks like there was a breaking change in oxmysql
