### ISSUE TITLE
Impound Bug

### ISSUE THREAD

**Issue by TonybynMp4** [JonasDev99/qb-garages#25]
The impound spawns the car even if you can't pay for it (because of the lines below)
i tried to fix it and couldn't figure out how that all worked so i hope you can figure it out
(the 2 recent PR's made me realize that but they don't actually fix it)

![image](https://user-images.githubusercontent.com/97451137/169674317-fff83956-832b-44d7-87de-6f955ef0ebf2.png)

**Comment by JonasDev99** [comment]
Should be fixed in the latest version

**Comment by TonybynMp4** [comment]
> Should be fixed in the latest version

doesn't look like it, the park last vehicle tells me i don't own the vehicle too btw

**Comment by JonasDev99** [comment]
Ok, I'll take another look
