### ISSUE TITLE
Liveries Not Sticking

### ISSUE THREAD

**Issue by xViperAG** [JonasDev99/qb-garages#29]
I have some cars that use a load of liveries and when I park a vehicle it changes the livery to something else

https://user-images.githubusercontent.com/82969741/169879481-e109e97e-d39b-4027-ad81-b6eb71391faa.mp4

Is there anything I can do to fix this?

**Comment by xViperAG** [comment]
Nevermind, Resolved.

Had to replace SQL.

**Comment by xViperAG** [comment]
Nevermind, I stand corrected, I'm still having the issue.

**Comment by MrJujuri** [comment]
what SQL you replace??
