### ISSUE TITLE
Latest QBCore issue

### ISSUE THREAD

**Issue by Roosterbrood** [JonasDev99/qb-garages#33]
[    567578] [b2545_GTAProce]        CrBrowserMain/ Icon "parking" could not be found, replacing a question mark. (@qb-radialmenu/html/js/RadialMenu.js:387)
[    567578] [b2545_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read property '0' of undefined (@qb-radialmenu/html/js/RadialMenu.js:403)

**Comment by JonasDev99** [comment]
Fixed
