### ISSUE TITLE
house garages 

### ISSUE THREAD

**Issue by Luceeiy** [JonasDev99/qb-garages#4]
when i add a car garage my car doesnt sit right in the drive way it comes out facing the direction of the door

**Comment by JonasDev99** [comment]
Did you define parking spots?

**Comment by JonasDev99** [comment]
Scratch that, yes house garages are like that

**Comment by Luceeiy** [comment]
is there a way to change that?

**Comment by JonasDev99** [comment]
I can update the code, what direction do you expect it to be? the direction you face when creating the garage?

**Comment by Luceeiy** [comment]
yes , im sure a lot of people are used to that

**Comment by JonasDev99** [comment]
Ok, I will see if its possible with just changing my script. It might require changes to the housing script, but I am not absolutely sure about that.

**Comment by JonasDev99** [comment]
It was just a minor issue. Go to client/main.lua and on line 504 change `garage.takeVehicle.w`  to  `garage.takeVehicle.h`
