### ISSUE TITLE
Shared garages

### ISSUE THREAD

**Issue by NiZiBiiT** [JonasDev99/qb-garages#45]
So with shared garages, I put the business or gang at the time in the shared part. And then in the game anyone can access the vehicles in the garage and it’s not just set to the gang only. This keeps happening. Is there a fix please?

**Comment by JonasDev99** [comment]
Can you share your config?

**Comment by NiZiBiiT** [comment]
Yeah sure! How do I send it?

**Comment by JonasDev99** [comment]
https://discord.gg/ZcrxXcqvJj

**Comment by Luma-exe** [comment]
Same thing happening to me

**Comment by JonasDev99** [comment]
> Same thing happening to me

If you make a gang garage, make sure to also set gang = 'vagos'
