### ISSUE TITLE
when i depot or impound as police vehicles the vehicles are in database but they cannot be spawned in any garage they are not available in depoto or impoundlot also

### ISSUE THREAD

**Issue by nepal4972** [JonasDev99/qb-garages#46]

**Comment by JonasDev99** [comment]
So Impound and Depot both work for me. Impound is not related to my garages:

![image](https://user-images.githubusercontent.com/25738474/175965201-678bee26-cb8b-4f18-a52b-b9f414e04182.png)

Depot is part of my garages but I tested it on my server and it works. Could you guys send me your configs so I can test it with them? 

Also did you say you impounded a police vehicle?

**Comment by nepal4972** [comment]
> So Impound and Depot both work for me. Impound is not related to my garages:
> 
> ![image](https://user-images.githubusercontent.com/25738474/175965201-678bee26-cb8b-4f18-a52b-b9f414e04182.png)
> 
> Depot is part of my garages but I tested it on my server and it works. Could you guys send me your configs so I can test it with them?
> 
> Also did you say you impounded a police vehicle?

i have depot my own vehicle but in depot that vehicle is not shown> But when i check my database the vehicle is not shown in depot. It shows in last garage. But when i change in Database parking as impountlot the vehicle is showing in Depot.

**Comment by nepal4972** [comment]
> So Impound and Depot both work for me. Impound is not related to my garages:
> 
> ![image](https://user-images.githubusercontent.com/25738474/175965201-678bee26-cb8b-4f18-a52b-b9f414e04182.png)
> 
> Depot is part of my garages but I tested it on my server and it works. Could you guys send me your configs so I can test it with them?
> 
> Also did you say you impounded a police vehicle?

Today i test depot no any issue but we have impound also if vechile is impounded where the vehicle goes?

**Comment by JonasDev99** [comment]
qb-policejob has an impound where only police can take out vehicles. Checkout qb-policejob config.lua to see where it is.
