### ISSUE TITLE
qb-garages error

### ISSUE THREAD

**Issue by cummins24v2** [JonasDev99/qb-garages#6]
![image](https://user-images.githubusercontent.com/97122395/161634537-89af6e01-5506-45cf-9933-3c1595e638bd.png)

**Comment by JonasDev99** [comment]
You're qb-core is outdated.
________________________________
From: cummins24v2 ***@***.***>
Sent: Monday, April 4, 2022 11:23:59 PM
To: JonasDev99/qb-garages ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JonasDev99/qb-garages] qb-garages error (Issue #6)


[image]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F97122395%2F161634537-89af6e01-5506-45cf-9933-3c1595e638bd.png&data=04%7C01%7Cjonas.suter%40fhnw.ch%7C6540f63af79e4b6732a408da1681713d%7C9d1a5fc8321e4101ae63530730711ac2%7C0%7C0%7C637847042445446600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sHbp4Apd4fT%2Fg0FK5sI7K3Hqe6ETnxcOqKG10mnQ%2F78%3D&reserved=0>
