### ISSUE TITLE
No Keys

### ISSUE THREAD

**Issue by TheMadkat03** [JonasDev99/qb-garages#61]
Every once and a while when a vehicle is pulled out  from a garage  it won't give the person their keys and i get these errors

[script:qb-vehiclekey] SCRIPT ERROR: @qb-vehiclekeys/server/main.lua:70: table index is nil
[ script:qb-garages] SCRIPT ERROR: @qb-garages/server/main.lua:41: table index is nil

**Comment by TheMadkat03** [comment]
[script:qb-vehiclekey] SCRIPT ERROR: @qb-vehiclekeys/server/main.lua:70: table index is nil
[   script:qb-garages] SCRIPT ERROR: @qb-garages/server/main.lua:41: table index is nil

**Comment by JonasDev99** [comment]
I believe this was a FiveM issue and was fixed by them afaik.
