### ISSUE TITLE
Depot not working

### ISSUE THREAD

**Issue by Erdenee423** [JonasDev99/qb-garages#71]
I When i use depot command depot car is going in depot but database not changing garage and i spawn depotod car car is spawning and i check the depot again the spawnad car in depot and i can spawn so many same cars. Can you please hurry fix this

**Comment by TonybynMp4** [comment]
it's in impound not depot

**Comment by TonybynMp4** [comment]
also please learn how to describe a problem this really hurts my brain

**Comment by Erdenee423** [comment]
My english is bad thats so i want police will impound with prices its that possible > learn

**Comment by TonybynMp4** [comment]
> My english is bad thats so i want police will impound cars with prices its that possible

policejob does that with the /impound command iirc

**Comment by Erdenee423** [comment]
> > My english is bad thats so i want police will impound cars with prices its that possible
> 
> 
> 
> policejob does that with the /impound command iirc

Yea i know but that not impounding with price if impound car its going in police impound i removed police impound

**Comment by Blaez** [comment]
When you do /depot (pricehere) it goes to the impound and the vehicle owner pulls the vehicle for the price specified in the command

**Comment by JonasDev99** [comment]
Should be fixed
