### ISSUE TITLE
[Question] Blips combine

### ISSUE THREAD

**Issue by OfficialRDB** [JonasDev99/qb-garages#77]
How would I combine the blips into like Public Parking instead of having them all separated ?
It looks like it is based on the label, because it does combine when it has the same name.

Why not based on a blip name or type ?

EDIT: Fixed
Removed the ` garage.label or  `

Another question is. If I go to impound I see my vehicle there, but it's not impounded because I'm standing next to it.
Should it not say, no vehicle impounded or something ?

Also I just duplicated my car at impound.

Spawning the vehicles says to far away, but it still spawn the vehicle where I stand.

If I use the jobGarageIdentifier = 'pd1', if returns a error if I open the garage.
![Capture](https://user-images.githubusercontent.com/50579206/197562780-9de67544-354f-49c7-a524-c835a11289fd.PNG)

**Comment by JonasDev99** [comment]
Most of these issues should be fixed in the latest version
