### ISSUE TITLE
Parking not all working

### ISSUE THREAD

**Issue by Andyauk** [JonasDev99/qb-garages#8]
The bell, the motel, liquor, beach are not working to put away, is it due to not having parking spaces in the code.

**Comment by JonasDev99** [comment]
Its only a wrong minZ. Works otherwise for me but thanks for reporting this.
![image](https://user-images.githubusercontent.com/25738474/162584300-f67cc182-339d-4554-bd18-11334e5fedf5.png)

**Comment by JonasDev99** [comment]
Set the minZ to something like this: 
![image](https://user-images.githubusercontent.com/25738474/162584350-d2d9582d-87c6-46f7-830e-aba9709115cf.png)

**Comment by Andyauk** [comment]
> Its only a wrong minZ. Works otherwise for me but thanks for reporting this. ![image](https://user-images.githubusercontent.com/25738474/162584300-f67cc182-339d-4554-bd18-11334e5fedf5.png)

Yes they used to work last week, but noticed today I couldn't put away, will you. E updating. Please thanks for the work

**Comment by Andyauk** [comment]
> Set the minZ to something like this: ![image](https://user-images.githubusercontent.com/25738474/162584350-d2d9582d-87c6-46f7-830e-aba9709115cf.png)

Kk thanks

**Comment by JonasDev99** [comment]
> Kk thanks

Did that work?

**Comment by JonasDev99** [comment]
should be fixed now, if you want to define parking lots then that's up to you

**Comment by Andyauk** [comment]
> should be fixed now, if you want to define parking lots then that's up to you

Thanks I'll check when I get home

**Comment by Andyauk** [comment]
All seems fine, but it was themotorhotel not motel parking.

**Comment by JonasDev99** [comment]
oh my bad
