### ISSUE TITLE
trying to get this working for qs-housing

### ISSUE THREAD

**Issue by kathryn2101** [JonasDev99/qb-garages#80]
hi i been using your garage for a while now and everyone loves it.

we just switched from qb-houses to qs-housing but having issues trying to figure out how i would configure the parking options to it all i get when i park is your vehicle cant be parked here and it doesnt park but i take it to a normal garage its fine, job garages are fine, gang garages are fine and depots are fine its literally just the housing side of things

any help would be much appreciated

this is what ive changed the HouseGarageCatagories to as my leo has a unmarked police cruiser for her personal vehicle that i would like parked at the house

`HouseGarageCategories = {'car', 'motorcycle', 'emergency', 'other'} -- Which categories are allowed to be parked at a house garage`

and im using your parkVehicle function and openMenu function for the houses but i cant park the car to even try out the house menu

**Comment by django1m** [comment]
Did you make it work ? i can park my car but cant open the menu to take out the car

**Comment by kathryn2101** [comment]
no i switched back to the original qb-garage

**Comment by JonasDev99** [comment]
Should be working with qs-housing now, no changes needed.
