### ISSUE TITLE
All house garages are accessible for everyone even without keys

### ISSUE THREAD

**Issue by SlimChances** [JonasDev99/qb-garages#83]
When a player walks over someone else's house garage without keys they can pull out any vehicle in that garage.

**Comment by OfficialRDB** [comment]
Just check, and I can confirm that this is a thing.

**Comment by didis97** [comment]
how to fix it pls ? gowan devvs my guys!

**Comment by didis97** [comment]
yeah same here

**Comment by SlimChances** [comment]
I have a pull request that fixed the issue

**Comment by SlimChances** [comment]
https://github.com/JonasDev99/qb-garages/pull/84

**Comment by JonasDev99** [comment]
This issue should be fixed in the latest version.
