### ISSUE TITLE
Add Config Option for Default Extras/Livery On Spawn (Used for job garages such as police, ems, fire)

### ISSUE THREAD

**Issue by EXPANS1VE** [JonasDev99/qb-garages#86]
It would be nice to add an option to the vehicle spawner where default extras and livery can be set, like to qb-policejob.

Right now it's random so police cars spawn with incomplete setups, ambulances spawn with doors off (toggled by extras), etc.

With the ability to define what livery and extras the car will spawn with every time, it makes it easier and more convenient for players to setup and get out on duty.

**Comment by JonasDev99** [comment]
this has been added

**Comment by EXPANS1VE** [comment]
I am on the latest version of this repo and do not see any livery or extra options for JobVehicle garages. Sorry to continue to pester for it, but I've tried doing this myself but have been unsuccessful in doing so. Any assistance would be greatly appreciated, thank you.
