### ISSUE TITLE
motelgarage for themotorhotel z change

### ISSUE THREAD

**Issue by Andyauk** [JonasDev99/qb-garages#9]
motelgarage you can put back to 44.0 or keep it as you changed it. as it works anyway,.
themotorhotel 37.78 to 36.78

**Comment by Andyauk** [comment]
ps, you also changed the coord for Impound, nice place to go, but you didn't move the main coords to there.

**Comment by JonasDev99** [comment]
> ps, you also changed the coord for Impound, nice place to go, but you didn't move the main coords to there.

I moved Impound to the Gabz Impound Lot near PDM on my sever but I am going to leave it at the old location in the config on github since not everyone has Gabz.
